### ISSUE TITLE
Research back-end

### ISSUE THREAD

**Issue by theartcher** [S3-Software-IP/monorepo#3]

**Comment by MorrisHannessen** [comment]
Good frameworks we can use with .net are: 

- Bot Framework SDK
Its from microsoft so it will work good with .net but its not an ai type of framework more like a "chatbot" framework. but i think that can help aswell.
- Wit.ia
its from facebook and is very good at making good ai reposes.
-BotSharp
just another good framework to help building an ai chatbot
