### ISSUE TITLE
[BUG] Images not showing up

### ISSUE THREAD

**Issue by MonkeyElite** [S3-Software-IP/monorepo#50]
**Describe the bug**
The c4 models in the README don't work. "File not found".

**To Reproduce**
1. Go to Readme
2. Files not work

**Expected behavior**
I expect the ability to see the images.

**Screenshots**
![image](https://github.com/S3-Software-IP/monorepo/assets/119488605/9038fdfc-3e45-44e9-b602-105ac4061cda)
![image](https://github.com/S3-Software-IP/monorepo/assets/119488605/8cb37893-0db7-43bc-9e0f-455edc638857)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera
 - Version: Unknown

**Comment by theartcher** [comment]
Behaviour recreated, working on a fix.

**Comment by theartcher** [comment]
Issue fixed, see #51.
